### ISSUE TITLE
删除文件时，getParam函数获得的是数组的时候htmlspecialchars会报错

### ISSUE THREAD

**Issue by WJsjtu** [fex-team/ufinder#10]
getParam函数获得的是数组的时候htmlspecialchars会报错，因为参数不是string
我的做法
if(is_array($res)){
        foreach ($res as $key => $value) {
            $res[$key] = htmlspecialchars($value);
        }
        return $res;
    }

**Comment by Jinqn** [comment]
同意这个做法.谢谢提醒,还没经过系统的测试,这个一直没发现,已修改.
