### ISSUE TITLE
Livereload Deprecated

### ISSUE THREAD

**Issue by WJsjtu** [fex-team/ufinder#11]
https://github.com/gruntjs/grunt-contrib-livereload 
Deprecated in favor of grunt-contrib-watch which now has Livereload support built-in.
livereload 不再支持了，发现npm install会出错，现在我只能去掉那部分的任务，希望能够更新为 grunt-contrib-watch

**Comment by Jinqn** [comment]
谢谢反馈,最近没使用这个插件,没发现,我把这个改成 grunt-contrib-watch 吧~
