### ISSUE TITLE
window.UFINDER_CONFIG被覆盖

### ISSUE THREAD

**Issue by WJsjtu** [fex-team/ufinder#13]
"defaultOptions": {
            'uploaderFileName': 'file',
            'uploaderSwfUrl': uf.getOption('URL') + '/lib/webuploader/Uploader.swf',
            'uploaderJsUrl': uf.getOption('URL') + '/lib/webuploader/webuploader.js'
        },

位置不清楚就是有一句setDefaultOptions中的$.extend(this._options, obj, true);执行之后，我在window.UFINDER_CONFIG中设置的uploaderSwfUrl和uploaderJsUrl会被覆盖。
是我的用法不对还是别的什么原因？

**Comment by Jinqn** [comment]
已修复这个问题,谢谢反馈
