### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by zenany** [fex-team/ufinder#2]
1. readme.md 是不是可以写详细点，介绍 ufinder 的背景、特点、使用方式
2. 代码结构上，是否可以参照业界典型的 php 应用的结构
3. 类、模块化支持、事件、ui和modal的分离等东西，在复杂应用中使用挺多的，kitty minder、ueditor、ufinder 中或多或少都存在，有没有可能抽象点东西出来

**Comment by Jinqn** [comment]
谢谢你的建议！
1. 这周正在在整理这些东西。
2. ufinder的代码结构沿用了之前做前端应用的结构，“典型的php应用的结构”，具体有没有什么例子可以参照？
3. 事件这块，这几个应用具体的需求都不一样，抽离出来有点麻烦；kityminder和ufinder都使用了umeditor的ui代码，这个分的比较开，有打算单独做维护，有时间再考虑把类定义的方式、模块化也一起整理出来。

**Comment by zenany** [comment]
php应用，可以参考 codeigniter 和 laravel 这两个php框架的。
另外，wordpress 和 joomla 的写得还不错，也可以参考。
期待你们抽象出快速开发应用的前后端一体化框架。
